[package]
name = "mbta"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = { version = "1.0.130", features = ["derive"] }
serde_yaml = "0.8.21"
reqwest = { version = "0.11.6", features = ["json", "blocking"] }
tokio = { version = "1.14.0", features = ["full"] }
